### ISSUE TITLE
Cross platform compilation

### ISSUE THREAD

**Issue by KirillovDenis** [nspcc-dev/tzhash#32]
Currently we cannot build anything with neofs SDK for ARM (e.g. `linux/arm/v6`,    `linux/arm/v7`, `linux/arm64`. Such platforms are used in https://github.com/nspcc-dev/distribution) because of AVX. 
Error example:
```
#0 1.022 # github.com/nspcc-dev/tzhash/gf127/avx
#0 1.022 vendor/github.com/nspcc-dev/tzhash/gf127/avx/gf127.go:23:6: missing function body
```

We should do something with this problem if we want to support another platforms.

Actually, there is another problem with some neofs-contract constants (they overflow int). It isn't directly related to this repo though:
https://github.com/nspcc-dev/neofs-contract/blob/a92ad8b8f0e7f5265bced249949ea7cbc9fdad75/nns/nns_contract.go#L49
https://github.com/nspcc-dev/neofs-contract/blob/a92ad8b8f0e7f5265bced249949ea7cbc9fdad75/nns/nns_contract.go#L67

P.S. Using vendor and drop unused (AVX, constants) allows build `distribution` for the following platforms:
* "linux/amd64",
* "linux/arm/v6",
*  "linux/arm/v7",
* "linux/arm64",
* "linux/ppc64le",
* "linux/s390x"

**Comment by fyrchik** [comment]
Could you try using `v1.6.0`?

**Comment by KirillovDenis** [comment]
The problems are gone using `v1.6.0`
